name: restore-yarn-cache
description: |
  Restore yarn cache
  requires yarn setup

outputs:
  cache-hit:
    description: 'Whether yarn cache hit or not'
    value: ${{ steps.restore-yarn-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory
      shell: bash
      run: |
        echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV

    - name: Restore yarn cache
      id: restore-yarn-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
