services:
  engineer-guild-hackathon:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/engineer-guild-hackathon:delegated
      - node_modules:/engineer-guild-hackathon/node_modules
      - client-node_modules:/engineer-guild-hackathon/packages/client/node_modules
      - server-node_modules:/engineer-guild-hackathon/packages/server/node_modules
    ports:
      # client
      - 3000:3000
      # server
      - 8000:8000
    working_dir: /engineer-guild-hackathon
    env_file:
      - .env
    depends_on:
      - db
    tty: true
  db:
    image: postgres:16.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

volumes:
  postgres-data:
  node_modules:
  client-node_modules:
  server-node_modules:
