name: ci

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'packages/**'
  workflow_dispatch:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.18.0]

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Get changed ts/tsx files
        id: get_changed_files
        run: |
          echo "files=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '\.ts[x]?$')" >> $GITHUB_OUTPUT

      - name: Build check
        run: yarn workspaces foreach run build

      - name: Run ESLint Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '${{ steps.get_changed_files.outputs.files }}'
          workdir: .
